apply plugin: 'com.android.application'\n\nandroid {\n    compileSdkVersion 31\n    defaultConfig {\n        applicationId "com.example.jarvisai"\n        minSdkVersion 21\n        targetSdkVersion 31\n        versionCode 1\n        versionName "1.0"\n    }\n    buildTypes {\n        release {\n            minifyEnabled false\n            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'\n        }\n    }\n}\n\ndependencies {\n    implementation 'com.android.support:appcompat-v7:31.0.0'\n    implementation 'com.android.support.constraint:constraint-layout:2.0.4'\n    implementation 'org.jetbrains.kotlin:kotlin-stdlib:1.5.0'\n}\n